# stack tests
a = 1;
a = 1 + 1;
print("These are a bunch of tests that i used for debugging the compiler and the virtual machine.");
print("All code in this file should be valid and should run without errors.");
print();

a = 42;
func => (q) {
    print("func");
    a = 1;
    print("inside function:    ", a);
    return a;
}

print("main");
print(a);
print("call func");
x = func(1);
print("func returned:      ", x);
print("verification of A: ", a);
print();

func2 => (a) {
    print("func2");
    print(a);
    return 3 * 33;
}

print("call func2: ", func2(11));
print();
x = 2 * 3 + 4 * 5;
print("x = 2 * 3 + 4 * 5 => ", x);
print();
y = 2 * (3 + 4) * 5;
print("y = 2 * (3 + 4) * 5 => ", y);
print();
if x > y {
    print("x > y");
} elif x == y {
    print("x == y");
} else {
    print("x < y");
}

list = [1, 2, 3, 4, 5];
rec = { "a": 1, "b": 2, "c": 3, "d": 4, "e": 5 };
print();
print(list);
print(rec);
print();
if 1 == 1 {
    print("1 == 1");
}

list = [1, 42, 3, 4, 5]; 
print($"did we mention {list[1]} already?");
print();
print(list);
foreach list {
    print(it);
}

print();
counter = 10;
print("countdown");
while counter > 0 {
    print(counter);
    counter = counter - 1;
    if counter == 7 {
        print("lucky number 42!");
        continue;
    }
    if counter == 5 {
        break;
    }
}


print();
print("Did you expect the countdown to skip 7 and print 'lucky number 42!' instead?");
print("And did you also expect the countdown to stop after 6?");

print();

var_1 = 12345;

switch var_1 {
    case 1: {
        print("case 1");
    }
    case 2: {
        print("case 2");
    }
    case 3: {
        print("case 3");
    }
    default: {
        print("The switch statement returns the default, because none of the values matched.");
    }
}

print();
print("end");
print();

print("This program will exit with error 42.");
print("This is correct and to be expected.");

print();

halt 42;