requesto/Exceptions.py,sha256=NwEvXYgwh25DdpQodiWpaAaezcftpBMVbWP7CL6Z-Qw,139
requesto/PostgresDb.py,sha256=Wbi9e1MgoUTf-Oa1jvPCnmSG-8H9Q4o70t3HCzO_IBE,2308
requesto/SqliteDb.py,sha256=t0vgf-GuuIQuSpt4NlO6a_sHi0QXhgNs_8BbLFRS4xE,1179
requesto/User.py,sha256=pvMyYsFsOhRM1wtS5_sa5XbK4hB1E-z1oW_IA0PdWa8,278
requesto/__init__.py,sha256=tVXThAxpmAtYAsqO5Fj7rygc6r6wmUzCNb690K8UMwA,1675
requesto/requesto.py,sha256=ZDqjavLcM642uBWf5veZPfSX-72w7e9sD9ACueSFrac,12586
requesto_py-1.2.0.dist-info/LICENSE,sha256=IwGE9guuL-ryRPEKi6wFPI_zOhg7zDZbTYuHbSt_SAk,35823
requesto_py-1.2.0.dist-info/METADATA,sha256=UqJAb1gLsCBN9bUgWwr2Ib2U-bCZsIT_1hnOC80thWc,2879
requesto_py-1.2.0.dist-info/WHEEL,sha256=GJ7t_kWBFywbagK5eo9IoUwLW6oyOeTKmQ-9iHFVNxQ,92
requesto_py-1.2.0.dist-info/top_level.txt,sha256=fey3LrbNa6nGb1EYpwPtm-Q4UxyLA7M1mmnptgpc274,9
requesto_py-1.2.0.dist-info/RECORD,,
